import type { StageDefinition, StageKey } from '@/types';

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    key: 'gemini_generate',
    name: 'Gemini: Generate Devotional Package',
    description: 'Use Gemini to generate the full devotional song package including lyrics, style notes, and vocal guidance.',
    service: 'gemini',
    index: 0,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 120_000,
    dependsOn: [],
  },
  {
    key: 'gemini_capture_parse',
    name: 'Parse Gemini Output',
    description: 'Capture and parse the Gemini response into structured lyrics, style, and metadata fields.',
    service: 'local',
    index: 1,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 10_000,
    dependsOn: ['gemini_generate'],
  },
  {
    key: 'chatgpt_lyrics_correct',
    name: 'ChatGPT: Lyrics Correction & Pronunciation',
    description: 'Use ChatGPT to correct lyrics, optimize pronunciation, and ensure devotional accuracy.',
    service: 'chatgpt',
    index: 2,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 120_000,
    dependsOn: ['gemini_capture_parse'],
  },
  {
    key: 'suno_generate',
    name: 'Suno: Generate Audio Candidates',
    description: 'Generate two music candidates (A and B) in Suno using corrected lyrics.',
    service: 'suno',
    index: 3,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 300_000,
    dependsOn: ['chatgpt_lyrics_correct'],
  },
  {
    // Runs in parallel with chatgpt_evaluate_candidate_b
    key: 'chatgpt_evaluate_candidate_a',
    name: 'ChatGPT: Evaluate Candidate A',
    description: 'Use ChatGPT to evaluate Suno candidate A and produce a structured assessment.',
    service: 'chatgpt',
    index: 4,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 120_000,
    dependsOn: ['suno_generate'],
  },
  {
    // Runs in parallel with chatgpt_evaluate_candidate_a
    key: 'chatgpt_evaluate_candidate_b',
    name: 'ChatGPT: Evaluate Candidate B',
    description: 'Use ChatGPT to evaluate Suno candidate B and produce a structured assessment.',
    service: 'chatgpt',
    index: 5,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 120_000,
    dependsOn: ['suno_generate'],
  },
  {
    key: 'chatgpt_auto_compare',
    name: 'ChatGPT: Auto-Compare Candidates',
    description: 'Upload both audio candidates to ChatGPT and receive a structured comparison with a recommended winner.',
    service: 'chatgpt',
    index: 6,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 180_000,
    dependsOn: ['chatgpt_evaluate_candidate_a', 'chatgpt_evaluate_candidate_b'],
  },
  {
    key: 'compare_candidates',
    name: 'Compare & Select Winning Audio',
    description: 'Present both candidates with evaluations to the user for selection. Pauses until human approves.',
    service: 'local',
    index: 7,
    isApprovalGate: true,
    maxAttempts: 1,
    timeoutMs: 0,
    dependsOn: ['chatgpt_auto_compare'],
    approvalType: 'winner_selection',
  },
  {
    // Runs in parallel with canva_prepare_thumbnails (both depend on compare_candidates)
    key: 'build_scene_plan',
    name: 'Build Scene Plan',
    description: 'Generate ~10-second scene segments based on the winning audio duration.',
    service: 'local',
    index: 8,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 10_000,
    dependsOn: ['compare_candidates'],
  },
  {
    key: 'refine_grok_prompts',
    name: 'ChatGPT: Refine Grok Prompts',
    description: 'Use ChatGPT to refine and optimize Grok video prompts for each scene.',
    service: 'chatgpt',
    index: 9,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 120_000,
    dependsOn: ['build_scene_plan'],
  },
  {
    key: 'grok_generate_scene_clips',
    name: 'Grok: Generate Scene Videos',
    description: 'Generate one video clip per scene using Grok text-to-video.',
    service: 'grok',
    index: 10,
    isApprovalGate: false,
    maxAttempts: 2,
    timeoutMs: 600_000,
    dependsOn: ['refine_grok_prompts'],
  },
  {
    // Runs in parallel with build_scene_plan→refine_grok_prompts→grok path
    key: 'canva_prepare_thumbnails',
    name: 'Canva: Prepare Thumbnails',
    description: 'Create and export thumbnail images using Canva based on the winning audio metadata.',
    service: 'canva',
    index: 11,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 300_000,
    dependsOn: ['compare_candidates'],
  },
  {
    key: 'capcut_handoff_package',
    name: 'CapCut: Package Handoff',
    description: 'Organize all assets into a CapCut-ready folder structure with a manifest.',
    service: 'capcut',
    index: 12,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 60_000,
    dependsOn: ['grok_generate_scene_clips', 'canva_prepare_thumbnails'],
  },
  {
    key: 'final_package',
    name: 'Final Package & Review',
    description: 'Compile final delivery package with all assets, manifests, and review checklist.',
    service: 'local',
    index: 13,
    isApprovalGate: false,
    maxAttempts: 3,
    timeoutMs: 30_000,
    dependsOn: ['capcut_handoff_package'],
  },
];

export const STAGE_MAP: Record<StageKey, StageDefinition> = Object.fromEntries(
  STAGE_DEFINITIONS.map(s => [s.key, s])
) as Record<StageKey, StageDefinition>;

export const TOTAL_STAGES = STAGE_DEFINITIONS.length;
